# Schema for the configuration files of the Simple A/B module.

simple_a_b.settings:
  type: config_object
  label: 'Simple A/B settings'
  mapping:
    reporting:
      type: string
      label: 'Reporting method'
    remember:
      type: string
      label: 'Remember method'
    remember_prefix:
      type: string
      label: 'Prefix'
    remember_lifetime:
      type: string
      label: 'Lifetime'
