<?php

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\simple_a_b\SimpleAB;

// this will be the id of the simple AB Type
// src/Plugin/SimpleABReport/BlockCustom.php
define('CONFIG_NAME', 'block_custom');

/**
 * Implements hook_help().
 */
function simple_a_b_blocks_help($route_name, RouteMatchInterface $route_match) {
}

/**
 * Implements hook_preprocess_block().
 */
function simple_a_b_blocks_preprocess_block(&$variables) {
  // found out the the provider is of type block_content
  $provider = isset($variables['configuration']['provider']) ? $variables['configuration']['provider'] : FALSE;
  $is_block_content = $provider === "block_content" ? TRUE : FALSE;

  // if we have a block_content block
  if ($is_block_content) {
    // load the block content
    $block_content = $variables['content']['#block_content'];

    // disable the default caching
    $variables['content']['#cache']['max-age'] = 0;

    // get the custom block id
    $id = $block_content->id();

    // load a list of the enabled custom blocks
    $config = \Drupal::service('simple_a_b.storage.config')->fetch(CONFIG_NAME);
    $eids = isset($config->data) ? $config->data : [];

    // look for the id in the list of eids
    // and return the tid (the key of the array)
    if (FALSE !== $tid = array_search($id, $eids)) {

      // if we have a tid
      // we can look it up to try and get the data for the this a/b test
      $test_data = \Drupal::service('simple_a_b.storage.data')->fetch($tid);

      // get the content and try and get its value
      // check if is array for input value ckeditor
      // TODO: this could be put in its on function as things get more complex
      $content = $test_data->content;
      if(is_array($content) && isset($content['value'])){
        $content = $content['value'];
      }

      // calculate the experience
      if (SimpleAB::calculateExperience($test_data)) {

        // replace the content
        $variables['content']['body']['0']['#text'] = $content;
      }
    }
  }
}
