<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function simple_a_b_blocks_help($route_name, RouteMatchInterface $route_match) {

}

/**
 * Implements hook_preprocess_block().
 */
function simple_a_b_blocks_preprocess_block(&$variables) {
  $block_content = isset($variables['content']['#block_content']) ? $variables['content']['#block_content'] : false;

  if($block_content){
    $id = $block_content->id();
    if($id === '1'){
      $variables['content']['body']['0']['#text'] = 'this is body, test here. check it out';
      $variables['content']['#cache']['max-age'] = 0;
      dpm($variables);
    }
  }
}
