<?php

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\google_analytics\Component\Render\GoogleAnalyticsJavaScriptSnippet;

/**
 * Implements hook_help().
 */
function simple_a_b_reports_google_help($route_name, RouteMatchInterface $route_match) {

}

function simple_a_b_reports_google_page_attachments(array &$page) {
  //  ga('send', 'event', [eventCategory], [eventAction], [eventLabel], [eventValue], [fieldsObject]);
  //
  //  Field Name	    Value Type	Required	  Description
  //  eventCategory	  text	      yes	        Typically the object that was interacted with (e.g. 'Video')
  //  eventAction	    text	      yes	        The type of interaction (e.g. 'play')
  //  eventLabel	    text	      no	        Useful for categorizing events (e.g. 'Fall Campaign')
  //  eventValue	    integer	    no	        A numeric value associated with the event (e.g. 42)

  //  $script = 'ga("send", "event", "simple a/b - my test" , "view", "variant 1", 1);';
  //
  //
  //  $page['#attached']['html_head'][] = [
  //    [
  //      '#tag' => 'script',
  //      '#value' => new GoogleAnalyticsJavaScriptSnippet($script),
  //    ],
  //    'simple_a_b_reports_google_tracking_code',
  //  ];
}

function _simple_a_b_reports_google_post_event($test_obj = [], $response = TRUE) {
  dpm($test_obj);
  dpm($response);
}
