<?php

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\simple_a_b_reports_google\SimpleABReportsGoogle;

/**
 * Implements hook_help().
 */
function simple_a_b_reports_google_help($route_name, RouteMatchInterface $route_match) {

}

/**
 * Implements hook_page_attachments().
 */
function simple_a_b_reports_google_page_attachments(array &$page) {
  // attach the js file
  $page['#attached']['library'][] = 'simple_a_b_reports_google/simple_a_b_reports_google';
}

/**
 * captures data sent from the report to this method
 * it is defined in the SimpleABReport plugin
 * see: /src/Plugin/SimpleABReport/GoogleAnalytics.php - "method"
 *
 * @param array $test_obj
 * @param bool $response
 */
function _simple_a_b_reports_google_post_event($test_obj = [], $response = TRUE) {
  $data = _simple_a_b_reports_google_prepare_event_data($test_obj, $response);
  SimpleABReportsGoogle::setReport($data);

}

/**
 * This method takes the data sent over to the reporter function and prepares
 * it for sending over to google analytics
 *
 * @param $test_obj
 * @param $response
 *
 * @return array
 */
function _simple_a_b_reports_google_prepare_event_data($test_obj, $response) {
  $output = [];

  $output['eventCategory'] = 'simple a/b - ' . $test_obj->name;
  $output['eventAction'] = 'view';
  $output['eventLabel'] = $response ? 'variant 1' : 'original';
  $output['eventValue'] = $test_obj->tid;
  $output['timeStamp'] = date('c');

  return $output;
}
